### ISSUE TITLE
Generate and publish a sitemap for the website on /sitemap

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/website#109]
We have a lot of pages and blogposts on the site that are not easy to discover. First step towards discovery would be publishing an autogeenrated sitemap on the website. This will provide a quick overview of what all content is on the site along with some hierarchy.

This is an example of the sitemap. We can come up with a visual design that fits our website.
![sitemap-example](https://github.com/tattle-made/website/assets/1415361/86fe0a3b-5b4b-4dfc-9d23-52de0f0acc5c)

**Comment by BudhiY16** [comment]
From what I have read, there can be broadly two types of sitemaps - one is the HTML, clickable kind for bettering visitor experience and the other is the more SEO-friendly XML kind. 

In terms of design that we can put up on the website, my preferred format/structure for the same would be something akin to a table of contents at the bottom of the home page like this screenshot

![Screenshot 2023-06-27 at 12 34 10 PM](https://github.com/tattle-made/website/assets/106575816/91fa1062-13b2-48ba-8f29-03c6cfdacbb3)

**Comment by dennyabrain** [comment]
I like this basic "Table of Content" style post here - https://www.computerenhance.com/p/table-of-contents
Nothing fancy but just important posts organized under headings.
![Screenshot 2023-08-10 at 07-40-16 Table of Contents](https://github.com/tattle-made/website/assets/1415361/43d3b4d2-f136-4f4a-9dcb-bebc16302037)
