### ISSUE TITLE
Add section for publications/media

### ISSUE THREAD

**Issue by tarunima** [tattle-made/website#11]
A page where we list publications, media coverage, talks, etc.

**Comment by dennyabrain** [comment]
@tarunima can you start fleshing out what examples of items in each section would look like? I'd like to sketch out a mock and submit for review

**Comment by tarunima** [comment]
the two papers we wrote last year, your hasGeek talk, the stakeholder map as a standalone image.

**Comment by dennyabrain** [comment]
how do you envision this page to be? just a feed of 'updates' (almost like a facebook feed)
or would it have sections?

**Comment by tarunima** [comment]
Just a feed of updates with links to the docs. Doesn't need to have sections at the moment.

**Comment by dennyabrain** [comment]
aah cool. 

thinking out loud - in that case, should we try a markdown only approach?
coz if we can just use headings, paragraphs, links, images, divider to build this page, it wont need any frontend dev effort.
though i can see how a custom design could make things pop a bit.

**Comment by tarunima** [comment]
yup. thats what I was thinking about. I feel like this issue is going to be assigned to me :-p.

**Comment by dennyabrain** [comment]
lol. I think we could do a markdown approach for now and close this tab. if it starts getting populated to an extent where it warrants some organization and highlights, we'll assign it to a designer+dev team.

**Comment by dennyabrain** [comment]
There is now an [Updates](https://tattle.co.in/updates) page on our website, which is where we'll record mentions of publications or features in Media. Think of it like a curated feed of wins :)
