### ISSUE TITLE
Fix website navigation on mobile

### ISSUE THREAD

**Issue by tarunima** [tattle-made/website#119]
This is what the navigation menu looks like on mobile:

![Screenshot_20230818_100837_Brave.jpg](https://github.com/tattle-made/website/assets/13188366/92bf89c7-4f23-4be2-9d70-bc79cf854f9d)

One can't click on the tabs buried under 'Research'.

**Comment by dennyabrain** [comment]
Looks like this now : 
![Screen Shot 2023-08-18 at 11 41 34](https://github.com/tattle-made/website/assets/1415361/b1b3e58e-caad-484a-a430-0a594550f551)
