### ISSUE TITLE
Add project based categorization for blog posts

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/website#135]
The way we have tags for every blog post and a way to filter by tags on the blog index page, lets allow people to explore blog posts based on projects.
So on the /blog page, we could have a section for projects with names of our projects. We could create project specific pages like this - https://tattle.co.in/blog/tags/devlog
we could set the url to be something like https://tattle.co.in/blog/tags/project/PROJECT_NAME. For instance https://tattle.co.in/blog/tags/project/uli or https://tattle.co.in/blog/tags/project/viral-spiral.

**Comment by maanasb01** [comment]
Hello, I would like to work on this issue. Please assign it to me, and please let me know if there are any specific details or guidelines I should follow.

Thanks!
