### ISSUE TITLE
Topic Modeling Images Are in Images Folder

### ISSUE THREAD

**Issue by tarunima** [tattle-made/website#17]
3 images on topic modeling that are not on the website are in the github folder. 
https://github.com/tattle-made/website/blob/master/src/images/topic-modelling-1.png

Should we move them to s3?

**Comment by dennyabrain** [comment]
i added these when i was experimenting with moving our blog to gatsby. since now we moved ahead with hosting those on ghost, these images are redundant/pointless. they can be deleted.

**Comment by tarunima** [comment]
deleted
