### ISSUE TITLE
Create dynamic sections on the homepage to highlight recent blogs and updates

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/website#174]

**Comment by maanasb01** [comment]
@dennyabrain. An idea for displaying the latest blogs and updates on the homepage. Here, the same components were used to render the blogs and updates used in their respective pages. 

**Blogs**
![latest blogs in homepage](https://github.com/user-attachments/assets/4477ba12-d5f9-4668-b2a7-23ee3909ec68)

**Updates**
![latest updates in homepage](https://github.com/user-attachments/assets/e637ba39-88c5-479f-8890-46c6a28d5041)

**Comment by aatmanvaidya** [comment]
issue resolved in PR https://github.com/tattle-made/website/pull/182
