### ISSUE TITLE
Accumulated pending small tasks on the website

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/website#29]
- [x] Make navigation section's padding responsive. it looks too cramped on mobile devices
- [x] Center the content of the landing page

**Comment by dennyabrain** [comment]
- [ ] Better images for case studies section

**Comment by dennyabrain** [comment]
-[ ] Landing page clips the text content on mobile

**Comment by dennyabrain** [comment]
- [ ] Redesign content for the section on the landing page about tattle's core infrastructure. Saakshita might send us a new design.
- [ ] The mailing list section is not responsive. Email id field and button look cramped on mobile screens.

**Comment by dennyabrain** [comment]
- [ ] Test the new updates page. @tarunima ping me here. when you are done with it.

**Comment by tarunima** [comment]
> * [x]  Test the new updates page. @tarunima ping me here. when you are done with it.

completed here: https://github.com/tattle-made/website/blob/master/src/pages/updates.mdx
might need to make changes after seeing rendering of table on the website.

**Comment by tarunima** [comment]
[] fix contributors' page:
    - add all names
    - possibly change layout

**Comment by dennyabrain** [comment]
- [ ] Add Content for Datasets Page
- [ ] link to zenodo checkmate dataset 
- [ ] link to khoj for Factchecking site dataset
- [ ] Create a page for External Dataset
	tattle.co.in/dataset/external-datasets
	markdown to be added by tarunima

**Comment by tarunima** [comment]
-[] Update English FAQ

**Comment by dennyabrain** [comment]
- [ ] Fix text on landing page in consultation with Saakshita. @tarunima

**Comment by dennyabrain** [comment]
- [ ] Review pages with sparse content like jodbot or whatsapp archiver

**Comment by dennyabrain** [comment]
- [ ] Add Datasets tab on the navigation bar

**Comment by dennyabrain** [comment]
- [ ] Add content for whatsapp scraper or drop it @tarunima

**Comment by tarunima** [comment]
> * [x]  Add content for whatsapp scraper or drop it @tarunima

done here: https://github.com/tattle-made/website/commit/8938cc00ed1ea0c8e212f67befd84c999d9fd1d3#diff-64b2d4d9b3bd2143d8815f711af7418839c67181ed9996ca88218734c32feb42

**Comment by tarunima** [comment]
-[ ] change loren ipsum on datasets page.

**Comment by dennyabrain** [comment]
- [ ] Can we update our privacy policy with new informatiion? @tarunima
