### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by tarunima** [tattle-made/website#4]
Accommodate a drop down for multiple product listings
Think of a language selection UI.

**Comment by tarunima** [comment]
Could use the image with Tattle written in multiple languages as a menu for language selection.

**Comment by dennyabrain** [comment]
I've moved the drop down issue to this -https://github.com/tattle-made/website/issues/8

**Comment by dennyabrain** [comment]
I've moved the Language selection issue here - https://github.com/tattle-made/website/issues/9

Closing this issue now.
