### ISSUE TITLE
Make Tattle Blog live again. 

### ISSUE THREAD

**Issue by tarunima** [tattle-made/website#48]
blog.tattle.co.in is down.

**Comment by dennyabrain** [comment]
Its back up. As usual the ghost instance shut down somehow. This happens like once in 5,6 months. 
I usually follow the steps here - https://docs.bitnami.com/bch/apps/ghost/administration/control-services/
tldr : 

1. ssh to the ec2
2. sudo /opt/bitnami/ctlscript.sh status (to check status of apache, ghost, sql)
3. sudo /opt/bitnami/ctlscript.sh restart ghost
