### ISSUE TITLE
Improve interaction on Community page

### ISSUE THREAD

**Issue by tarunima** [tattle-made/website#49]
At present, it isn't clear that clicking the contributors name on https://tattle.co.in/community/ will take you to their webpage. Can consider following options to improve interaction:

- Add text describing purpose of clicking
- Add icon
- Create separate text such as: 'Go To Personal Website'

**Comment by dennyabrain** [comment]
https://github.com/tattle-made/website/commit/24160b82afcdf16ab151453ff516708e089f9a43 fixes this.
