### ISSUE TITLE
direct gettattle.app to tattle.co.in

### ISSUE THREAD

**Issue by tarunima** [tattle-made/website#5]

**Comment by RishavT** [comment]
I can take a look at this, have worked with domains and stuff. Also, Hi @dennyabrain !

If a redirect is OK, simple hack if nothing else works:
- upload a page to github.io which redirects to tattle.co.in:
    ```
    while (true) { window.location.href = "https://tattle.co.in/"; }
    ```
    Along with a link `You should be redirected soon. if not, click here`

**Comment by dennyabrain** [comment]
hi @RishavT !!!
ok your "nothing else" solution is actually quite acceptable too. 

You'll need both namecheap and route53 (AWS) credentials for this. Could you share an email or something where i could send these? you can share it non publically via @tarunima.

**Comment by RishavT** [comment]
Awesome! You should find my email on my github profile - I'll also give it to @tarunima tomorrow :)

**Comment by dennyabrain** [comment]
oh yeah i see it on your profile. will email.
