### ISSUE TITLE
Add Product Description

### ISSUE THREAD

**Issue by tarunima** [tattle-made/website#7]
Add a tab with description as well as link to the product, for the following products:

- Tattle Archive (Kosh)
- Telegram Bot (JodBot)
- Tattle Search (Khoj)

Sections that must exist on each page:
-  What does the product do?
-  Github link
-  Go to product site

**Comment by dennyabrain** [comment]
@tarunima an idea
I think we should mention on the product page who all are currently using that product.
we can keep things vague where revealing an individual's identity is not required or not allowed but would be nice to give some context on who we made the tool for etc

**Comment by dennyabrain** [comment]
I've made place holder pages for these and pushed to feature/may13-sprint. you can add content there.

we'll merge to master and deploy after the sprint

**Comment by tarunima** [comment]
Added text to the three products. Could you please confirm on the code repository link here: https://github.com/tattle-made/website/blob/feature/may13-sprint/src/pages/products/khoj.mdx

**Comment by dennyabrain** [comment]
yes. looks good to me. will notify when i deploy
