### ISSUE TITLE
Relocate Page Heading to Navigation Bar

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/website#87]
A proposal to make a visual change to the website.

### Current Layout
Currently a page heading looks like this on the website : 
![Screenshot 2022-10-18 at 10-20-17 Tattle - Tattle](https://user-images.githubusercontent.com/1415361/196338232-af175fae-9b8c-49d4-9895-39f4360e251d.png)

### Proposed Improvement
![Screenshot 2022-10-18 at 10-25-08 Tattle - Tattle](https://user-images.githubusercontent.com/1415361/196339351-6a0c680c-daa9-4cd1-b2c1-6f28e08236aa.png)

### Rationale
I think it utilizes space better and brings the page content to focus.

### Roadblocks
As of now page headings are part of the markdown file, we'll need some way to pass that information to the navigation component. I'd prefer if this is done at the gatsby level - maybe configure gatsby to get this information from a node as opposed to passing it via prop. Ideas for implementation are welcome.

**Comment by Harsh-garg-coder** [comment]
can you assign this issue to me?
